# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Univariate cumulative normal (distribution function)
#' 
#' Based on the paper "Better approximations to cumulative normal functions" by 
#' G. West \url{http://www.wilmott.com/pdfs/090721_west.pdf}. The source code
#' has been taken from the authors webpage \url{http://finmod.co.za/research.html}.
#' 
#' @param x Value of quantiles.
#' @param mean The mean.
#' @param sd The standard deviation.
#' @return The distribution function.
#' @author Lars Relund \email{lars@@relund.dk}
#' @export
pNorm1D <- function(x, mean, sd) {
    .Call('hmdpPricePigIT_pNorm1D', PACKAGE = 'hmdpPricePigIT', x, mean, sd)
}

#' Bivariate cumulative normal (distribution function) using Armadillo
#' 
#' Based on the paper "Better approximations to cumulative normal functions" by 
#' G. West \url{http://www.wilmott.com/pdfs/090721_west.pdf}. The source code
#' has been taken from the authors webpage \url{http://finmod.co.za/research.html}.
#' 
#' Transform into a bivariate with sd = 1 using Y = 1/sqrt(diag(sigma))(X-mean), i.e.
#' Pr(X<=x) = P(Y<=1/sqrt(diag(sigma))(x-mean)).
#' 
#' @param lower The vector of lower limits (2-dim vector).
#' @param upper The vector of upper limits (2-dim vector).
#' @param mean The mean vector (2-dim vector).
#' @param sigma The covariance matrix (2x2). 
#' @return The distribution function.
#' @author Lars Relund \email{lars@@relund.dk}
#' @export
pNorm2D_arma <- function(lower, upper, mean, sigma) {
    .Call('hmdpPricePigIT_pNorm2D_arma', PACKAGE = 'hmdpPricePigIT', lower, upper, mean, sigma)
}

#' Bivariate cumulative normal (distribution function)
#' 
#' Based on the paper "Better approximations to cumulative normal functions" by 
#' G. West \url{http://www.wilmott.com/pdfs/090721_west.pdf}. The source code
#' has been taken from the authors webpage \url{http://finmod.co.za/research.html}.
#' 
#' Transform into a bivariate with sd = 1 using Y = 1/sqrt(diag(sigma))(X-mean), i.e.
#' Pr(X<=x) = P(Y<=1/sqrt(diag(sigma))(x-mean)).
#' 
#' @param lower The vector of lower limits (2-dim vector).
#' @param upper The vector of upper limits (2-dim vector).
#' @param mean The mean vector (2-dim vector).
#' @param sigma The covariance matrix (2x2). 
#' @return The distribution function.
#' @author Lars Relund \email{lars@@relund.dk}
#' @export
pNorm2D <- function(lower, upper, mean, sigma) {
    .Call('hmdpPricePigIT_pNorm2D', PACKAGE = 'hmdpPricePigIT', lower, upper, mean, sigma)
}

#' Build the HMDP (2 levels with shared linking) using the C++ binary writer. 
#' 
#' @param filePrefix Prefix used by the binary files storing the MDP model.
#' @param param Model parameters of the HMDP.
#' @param paramDLMPi A list including the parameters for the DLMW (DLM for weigh information). 
#' @param paramDLMP A list including the parameters for the DLMP (DLM for pork price information). 
#' @param paramDLMF A list including the parameters for the DLMF (DLM for feed price information) 
#' @param paramPolicy A given policy for the hmdp. In finding the optimal policy of the HMDP, this policy will not be used. 
#' 
#' @return Build log (character).
#' @author Lars Relund \email{lars@@relund.dk}, Reza Pourmoayed \email{rpourmoayed@@econ.au.dk}
#' @export
BuildHMDP2 <- function(filePrefix, param, paramDLMP, paramDLMPi, paramDLMF, paramPolicy) {
    .Call('hmdpPricePigIT_BuildHMDP2', PACKAGE = 'hmdpPricePigIT', filePrefix, param, paramDLMP, paramDLMPi, paramDLMF, paramPolicy)
}

#' Calculate the reward of seeling and the feed intake of the pigs in an unselected pen using simulation.
#' 
#' @param pigs Number of pigs in the pen.
#' @param samples Number of samples in the simulation.  
#' @param weeks Number of weeks in a production cycle.
#' @param prices Set of possible prices for the carcass.
#' @param V Covariance matrix of the RRM model for the random parameters.
#' @param B Fixed parameters of the RRM model.  
#' @param R Standard deviation of residual error in the RRM model.
#' 
#' @return A list used in R including the weight, growth, leanness, 
#' and the reward of sorted pigs in the pen. 
#' @export
SimulatePigs <- function(pigs, samples, weeks, prices, V, B, R) {
    .Call('hmdpPricePigIT_SimulatePigs', PACKAGE = 'hmdpPricePigIT', pigs, samples, weeks, prices, V, B, R)
}

